# Generated by Django 5.2.2 on 2025-10-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default profile.png', null=True, upload_to=''),
        ),
    ]
