# Generated by Django 5.2.2 on 2025-06-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desscription',
            new_name='description',
        ),
    ]
